# global settings
output_dir: data/
crs: EPSG:32604
output_name: hi_nhf_1.2.3.gpkg # If not specified, will default to version

# hf builds
build:
  reference_divides_path: data/reference/hi_0.1.8_reference_divides.parquet
  reference_flowpaths_path: data/reference/hi_0.1.8_reference_flowpaths.parquet
  # debug_outlet_count: 2000 # If specified, only the total amount of rivers here will be built
  divide_aggregation_threshold: 3.0

# choose tasks to run
tasks:
  build_hydrofabric: True
  divide_attributes: True
  flowpath_attributes: True
  hydrolocations: True
  gages: True
  lakes: True
  fp_crosswalk: True
  validate_hf: True
  res_da: True

# flowpaths
flowpath_attributes:
  flowpath_id: fp_id
  use_stream_order: True
  dem_path: data/hi/divide-attributes/usgs/hi_dem_250.tif

# divide attributes
divide_attributes:
  processes: 1
  data_dir: data/hi/divide-attributes
  divide_id: div_id
  tmp_dir: data/hi/tmp/divide-attributes
  split_vpu: False
  debug: False
  attributes: # attributes must be specified - there are no defaults
    bexp1:
      file_name: nwm/bexp_0.tif
      agg_type: mode
      field_name: bexp_mode
    isltyp:
      file_name: nwm/ISLTYP.tif
      agg_type: mode
      field_name: isltyp_mode
    ivgtyp:
      file_name: nwm/IVGTYP.tif
      agg_type: mode
      field_name: ivgtyp_mode
    dksat:
      file_name: nwm/dksat_0.tif
      agg_type: weighted_geometric_mean
      field_name: dksat_geomean
    psisat:
      file_name: nwm/psisat_0.tif
      agg_type: weighted_geometric_mean
      field_name: psisat_geomean
    cwpvt:
      file_name: nwm/cwpvt.tif
      agg_type: mean
      field_name: cwpvt_mean
    mp:
      file_name: nwm/mp.tif
      agg_type: mean
      field_name: mp_mean
    mfsno:
      file_name: nwm/mfsno.tif
      agg_type: mean
      field_name: mfsno_mean
    quartz:
      file_name: nwm/quartz_0.tif
      agg_type: mean
      field_name: quartz_mean
    refkdt:
      file_name: nwm/refkdt.tif
      agg_type: mean
      field_name: refkdt_mean
    slope_1km:
      file_name: nwm/slope.tif
      agg_type: mean
      field_name: slope1km_mean
    smcmax:
      file_name: nwm/smcmax_0.tif
      agg_type: mean
      field_name: smcmax_mean
    smcwlt:
      file_name: nwm/smcwlt_0.tif
      agg_type: mean
      field_name: smcwlt_mean
    vcmx:
      file_name: nwm/vcmx25.tif
      agg_type: mean
      field_name: vcmx_mean
    impervious:
      file_name: impervious/hi_full_imperv_percent.tif
      agg_type: mean
      field_name: imperv_mean
    twi:
      file_name: twi/twi_hi.tif
      agg_type: quartile_dist
      field_name: twi_quartile
    twi_2:                      # another twi option
      file_name: twi/twi_hi.tif
      agg_type: quantile_dist
      field_name: twi_quantile
    elevation:
      file_name: usgs/hi_dem_250.tif
      agg_type: mean
      field_name: elevation_mean
    slope:
      file_name: usgs/hi_slope_250.tif
      agg_type: mean
      field_name: slope250m_mean
    aspect:
      file_name: usgs/hi_aspect_250.tif
      agg_type: weighted_circular_mean
      field_name: aspect_circmean
    axaj:
      file_name: nwm/AXAJ.tif
      agg_type: mean
      field_name: a_xinanjiang_inflection_point_parameter
    bxaj:
      file_name: nwm/BXAJ.tif
      agg_type: mean
      field_name: b_xinanjiang_shape_parameter
    xxaj:
      file_name: nwm/XXAJ.tif
      agg_type: mean
      field_name: x_xinanjiang_shape_parameter
    coeff:
      file_name: gw/coeff.tif
      agg_type: mean
      field_name: cgw
    expon:
      file_name: gw/expon.tif
      agg_type: mean
      field_name: expon
    zmax:
      file_name: gw/zmax.tif
      agg_type: mean
      field_name: max_gw_storage
    lzfpm:
      file_name: sac-sma/LZFPM.tif
      agg_type: mean
      field_name: lzfpm_mean
    lzpk:
      file_name: sac-sma/LZPK.tif
      agg_type: mean
      field_name: lzpk_mean
    lztwm:
      file_name: sac-sma/LZTWM.tif
      agg_type: mean
      field_name: lztwm_mean
    rexp:
      file_name: sac-sma/REXP.tif
      agg_type: mean
      field_name: rexp_mean
    uzk:
      file_name: sac-sma/UZK.tif
      agg_type: mean
      field_name: uzk_mean
    zperc:
      file_name: sac-sma/ZPERC.tif
      agg_type: mean
      field_name: zperc_mean
    lzfsm:
      file_name: sac-sma/LZFSM.tif
      agg_type: mean
      field_name: lzfsm_mean
    lzsk:
      file_name: sac-sma/LZSK.tif
      agg_type: mean
      field_name: lzsk_mean
    pfree:
      file_name: sac-sma/PFREE.tif
      agg_type: mean
      field_name: pfree_mean
    uzfwm:
      file_name: sac-sma/UZFWM.tif
      agg_type: mean
      field_name: uzfwm_mean
    uztwm:
      file_name: sac-sma/UZTWM.tif
      agg_type: mean
      field_name: uztwm_mean
    vegetation_height:
      file_name: pet/veg_height.tif
      agg_type: mean
      field_name: vegetation_height
    zero_plane_displacement_height:
      file_name: pet/zero_plane.tif
      agg_type: mean
      field_name: zero_plane_displacement_height
    momentum_transfer_roughness_length:
      file_name: pet/momentum_transfer.tif
      agg_type: mean
      field_name: momentum_transfer_roughness_length
    heat_transfer_roughness_length:
      file_name: pet/heat_transfer.tif
      agg_type: mean
      field_name: heat_transfer_roughness_length
    surface_longwave_emissivity:
      file_name: pet/longwave_emissivity.tif
      agg_type: mean
      field_name: surface_longwave_emissivity
    surface_shortwave_albedo:
      file_name: pet/shortwave_albedo.tif
      agg_type: mean
      field_name: surface_shortwave_albedo


gages:
  gages:
    inputs:
      usgs_discontinued:
        dir: usgs_gages_discontinued
        gage_source_crs: EPSG:4326
        id_col_name: site_no
      usgs_active:
        dir: usgs_active_gages
        id_col_name: site_no
      CIROH_UA:
        path: CIROH_UA/gage_area.csv
        id_col_name: gage
        area_col_name: area_sqkm
      nwm_calib_gages:
        path: nwm_calib/nwm_calib_gages_07112025.csv
        gage_source_crs: EPSG:4326
        id_col_name: site_no
      routelink:
        path: routelink/RouteLink_HI_EPSG4326.gpkg
        gage_source_crs: EPSG:4326
        id_col_name: gages
      other:
        path: other/gage_xy_v1.1.csv
        gage_source_crs: EPSG:4326
        id_col_name: site_no
        x_col_name: lon
        y_col_name: lat
      rfc:
        path: rfc/nwps_all_gauges_report.csv
        id_col_name: nws shef id
        status_col_name: forecast status
        x_col_name: longitude
        y_col_name: latitude
        gage_source_crs: EPSG:4326
    target:
      crs: EPSG:32604
      snap_tolerance_m: 100.0
      update_existing: True
      exclude_ids: []
      out_gpkg: gages/gages_hi.gpkg
      gpkg_layer_name: gages

  ###--------------------------------------------
  ## A file for USGS upstream area and basins shapefiles
  ###--------------------------------------------
  NLDI_upstream_basins:
    run_NLDI_upstream_basins: False # OCONUS does not have upstream basins
    path: nldi_upstream_basins.gpkg
    layer_polys: NLDI_upstream_basins
    layer_points: "sites"

  ###--------------------------------------------
  ##SNAPPING FLOWPATHS TO GAGES based on upstream catchments area
  ###--------------------------------------------
  assign_fp_to_gages:
   rel_err: 0.25                    # relative acceptable error between total upstream area and USGS upstream area.
   buffer_m: 1000.0                 # Buffering around point gages to find flowpaths. in meters
   parallel: False                  # serial (False) or parallel (True)
   max_workers: null                  # None: if serial
   USGS_NLDI_crs: EPSG:4326      # usgs crs used in NLDI API. more info: https://waterdata.usgs.gov/blog/nldi-intro/
   work_crs: EPSG:32604           # an area-equal crs to calculate buffers and distances

# --------------------------------------------------
# validate hydrofabric
# --------------------------------------------------
validate_hf:
  calibration_gages_path: data/gages/validation/calibratable_gages.csv
  routelink_gages_path: data/gages/routelink/RouteLink_HI_EPSG4326.gpkg

#---------------------------------------------------
# flowpath crosswalk (fp_crosswalk)
# --------------------------------------------------
fp_crosswalk:
  # reference (file1) – usually hydrofabric reference flowpaths
  reference:
    id_col: flowpath_id                     # id1_col in code

  # target network (file2) – e.g., NWM or NHDPlus
  target:
    path: data/reference/nwm_flows.gpkg               # <- file2
    layer: nwm_streams                     # layer2 in code
    id_col: ID                             # id2_col in code

  # geometric / matching parameters
  search_radius_m: 10.0       # buffer radius around each reference flowline
  percent_inside_min: 0.005    # min pct of matched path inside band for single-candidate shortcut

  outputs:
    # final full-table crosswalk output
    path: data/nhd-crosswalk/nhd_crosswalk_hi.parquet

#---------------------------------------------------
# lakes
#---------------------------------------------------
lakes:
  input_dir: "./data/hi/lakes/"
  vfp_lake_crosswalk: True
  calculate_elevation: False # Hawaii is joined to existing data and does not need new elevation
  use_cached_lakes: False
  output_comid_field: "lake_id"
  lakes_path: "output/hi_lakes.gpkg"
  validate_duplicates: False # flag to search for duplicate lake points during lakes validation. Defaults to true
  save_duplicate_gpkgs: False # flag to (in addition to normal output) save the resulting duplicate lake points/polygons as geopackages. Defaults to false
  nwm:
    run: True
    associate_flowpaths: True # this will run the flowpath association
    path: "input/nwm_lakes_hi_input.gpkg"
    layer: "nwm_lakes"
    fp_associated_path: "output/hi_lakes_fp_associated.gpkg" # can be empty or populated
    improve_placement_ref_res: False # no ref res in oCONUS
    flowpath_association_method: "polygon_outlet"
    populate_hydaulics: True
    id_field: "newID"
    search_radius_m: 25000
    attrib_src_path: "input/hi_nextgen_workaround.gpkg" # file to get attributes from
    attrib_src_layer: "lakes"
    attrib_src_key: "lake_id"
  adhoc:
    run: False
  ref_res:
    run: False # No reference reservoirs in HI
  ref_wb:
    run: False # No reference waterbodies in HI
  nid:
    path: input/NID2019_U.csv
  dem:
    path: input/hi_dem_250.tif # Generally HI does not need elevation, but store USGS DEM here if so

res_da:
  input_dir: "./data/hi/lakes/"
  lake_id_field: "lake_id"
  gage_id_field: "site_no"
  da_type_field: "da_type"
  great_lakes: False
  all_level_pool: True
  generate_additional_crosswalk: False
  adhoc:
    run: False
  usace:
    run: False
  usbr:
    run: False
